package com.brocade.dcm.domain.mapper;

import com.brocade.dcm.domain.model.Dept;
import com.brocade.dcm.domain.model.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    long countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int deleteByPrimaryKey(Integer deptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    Dept selectByPrimaryKey(Integer deptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dept
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByPrimaryKey(Dept record);
}