package com.brocade.dcm.domain.mapper;

import com.brocade.dcm.domain.model.Emp;
import com.brocade.dcm.domain.model.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int deleteByPrimaryKey(Integer empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    Emp selectByPrimaryKey(Integer empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.emp
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    int updateByPrimaryKey(Emp record);
}