package com.brocade.dcm.domain.model;

import java.util.Date;
import java.util.Objects;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.empno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.ename
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.job
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.mgr
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Integer mgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.hiredate
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Date hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.sal
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Integer sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.comm
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Integer comm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.emp.deptno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Integer deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.empno
     *
     * @return the value of public.emp.empno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.empno
     *
     * @param empno the value for public.emp.empno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.ename
     *
     * @return the value of public.emp.ename
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.ename
     *
     * @param ename the value for public.emp.ename
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.job
     *
     * @return the value of public.emp.job
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.job
     *
     * @param job the value for public.emp.job
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.mgr
     *
     * @return the value of public.emp.mgr
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Integer getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.mgr
     *
     * @param mgr the value for public.emp.mgr
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setMgr(Integer mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.hiredate
     *
     * @return the value of public.emp.hiredate
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.hiredate
     *
     * @param hiredate the value for public.emp.hiredate
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.sal
     *
     * @return the value of public.emp.sal
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Integer getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.sal
     *
     * @param sal the value for public.emp.sal
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setSal(Integer sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.comm
     *
     * @return the value of public.emp.comm
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Integer getComm() {
        return comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.comm
     *
     * @param comm the value for public.emp.comm
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setComm(Integer comm) {
        this.comm = comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.emp.deptno
     *
     * @return the value of public.emp.deptno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.emp.deptno
     *
     * @param deptno the value for public.emp.deptno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Objects.hashCode(empno);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Emp other = (Emp) obj;
		if (Objects.equals(empno, other.empno)) {
			System.out.println("*********EQUALS HIT CHECK*********");
			return true;
		}
		return false;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Emp [empno=").append(empno).append(", ename=").append(ename).append(", job=").append(job)
				.append(", mgr=").append(mgr).append(", hiredate=").append(hiredate).append(", sal=").append(sal)
				.append(", comm=").append(comm).append(", deptno=").append(deptno).append("]");
		return builder.toString();
	}
}