package com.brocade.dcm.domain.model;

import java.util.Date;
import java.util.Objects;

public class Posts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.id
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.title
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.description
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.creationdate
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.author
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.id
     *
     * @return the value of public.posts.id
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.id
     *
     * @param id the value for public.posts.id
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.title
     *
     * @return the value of public.posts.title
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.title
     *
     * @param title the value for public.posts.title
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.description
     *
     * @return the value of public.posts.description
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.description
     *
     * @param description the value for public.posts.description
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.creationdate
     *
     * @return the value of public.posts.creationdate
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.creationdate
     *
     * @param creationdate the value for public.posts.creationdate
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.author
     *
     * @return the value of public.posts.author
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.author
     *
     * @param author the value for public.posts.author
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Objects.hashCode(id);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Posts other = (Posts) obj;
		if (Objects.equals(id, other.id)) {
			System.out.println("*********EQUALS HIT CHECK*********");
			return true;
		}
		return false;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Posts [id=").append(id).append(", title=").append(title).append(", description=")
				.append(description).append(", creationdate=").append(creationdate).append(", author=").append(author)
				.append("]");
		return builder.toString();
	}
}